<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>6bf1596c-0642-43d4-92aa-674da785d6e6</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\backend\MyApp.Api\MyApp.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    </ItemGroup>

</Project>
